ical4j/ical4j

- src/main/java/net/fortuna/ical4j/model/Recur.java
- src/test/java/net/fortuna/ical4j/model/RecurTest.java
This fixes rules like
```
RRULE: FREQ=MONTHLY;WKST=FR;COUNT=3;INTERVAL=1;BYMONTH=1,9,10,12;BYMONTHDAY=12
```
> Issue #47 Fix counting of filtered out dates

- build.gradle
Accidentally noticed the problem today when their maven repository was down and I was not able to build iCal4j because of that. I do not think this project needs svn dependency anyway.
> Removed svnkit transitional dependency from the build

- src/main/java/net/fortuna/ical4j/model/Date.java
As the java.util.Date class is more or less deprecated, and in the examples of ical4j the Calendar is just to deal with this.
It makes sense to add a constructor which takes a Calendar value.
> Add constructor to take Calendar value

- src/main/java/net/fortuna/ical4j/model/Period.java
The definition of "greater" was ambiguous (longer period?  later start?
later end?); this pull request improves it somewhat.
> Clarify documentation of Period.compareTo

- src/main/java/net/fortuna/ical4j/model/Dur.java
- src/test/java/net/fortuna/ical4j/model/DurTest.java
updated Dur constructor that takes 2 dates to use `long` precision for tracking the duration difference.
this fixes #94 where dates which have a difference in seconds greater than `Integer.MAX_VALUE` would incorrectly calculate duration due to Integer overflow.
> Fixes #94 Integer overflow issue in Dur construction

- src/main/java/net/fortuna/ical4j/model/property/DateProperty.java
- src/test/java/net/fortuna/ical4j/model/property/DatePropertyTest.java
When no date is set, calling `copy()` and `hashCode()` resulted in NPE.
I stumbled upon this bug using the following ical constellation. The VALARM trigger created a date property which was null, so calling `hashValue()` on the event resulted in an NPE.
```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Smry
DESCRIPTION:Dscr
LOCATION:Loc
DTSTART:20150219T180000Z
DTEND:20150219T225959Z
CLASS:DEFAULT
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR
```
> Fixed NPE in DateProperty

- src/main/java/net/fortuna/ical4j/data/CalendarBuilder.java
- src/main/java/net/fortuna/ical4j/model/Component.java
- src/main/java/net/fortuna/ical4j/model/ComponentFactoryImpl.java
- src/test/java/net/fortuna/ical4j/data/CalendarBuilderConcurrencyTest.java
Building calendar was failing in concurrent environment because of static ComponentFactoryImpl reference.
If you run CalendarBuilderConcurrencyTest on the old code, it will fail.
> Removed concurrency issue

- build.gradle
As request in #122 we would mark groovy and bnd as maven optional (non transitive) dependencies and also marks their OSGi import package as optional.
Reference:
* https://blog.gradle.org/introducing-compile-only-dependencies
* https://github.com/gradle/gradle/issues/867
* https://docs.gradle.org/3.3/userguide/osgi_plugin.html
deployed pom.xml in our organisation maven repository
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>org.mnode.ical4j</groupId>
<artifactId>ical4j</artifactId>
<version>2.0.1-develop-SNAPSHOT</version>
...
<dependencies>
... …
```
> Mark groovy and bdn as non transivive dependencies and optional in OSGi

- src/main/java/net/fortuna/ical4j/model/TimeZoneRegistryImpl.java
Catch NullPointerException in TimeZoneRegistryImpl when tz.alias is missing. Fixes #201.
> Handle NullPointerException when tz.alias is missing #201

- src/main/java/net/fortuna/ical4j/util/UidGenerator.java
The hostname is cached by UidGenerator instance, cf #157 
About the tests, `testShouldSerializeDeserializeCorrectly()` was already in failure before the modification.
> #157 Cache InetAddressHostInfo.getHostName() value

- LICENSE
This patch changes the formatting of the ical4j license to the default
formatting for the 3-Clause-BSD license used by Github. This causes
Github to recognize the license and display license information for it.
Note that this changes only the formatting of the license with two
exceptions:
```diff
- Neither the name of Ben Fortuna nor the names of any other contributors may be used
+ Neither the name of the copyright holder nor the names of its contributors may be used
```
```diff
- IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
+ IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
```
I hope that these changes are ok.
The reasoning for this pull request is that I was approached by by one
of the Apereo Foundation projects to check if this custom license is ok …
> Make Github recognize the license

- src/main/java/net/fortuna/ical4j/model/Recur.java
- src/test/java/net/fortuna/ical4j/model/RecurTest.java
This is a fix for the changes introduced from issue #174 . Given an invalid date, after 12 trials (multiplier > 12) we should return null as no valid date is possible however the loop currently runs infinitely. A fix is included by making the condition strict to only loop when we haven't hit a valid date and we still can increment further. If we reach the valid date or pass max increments then we break and return result as null.
Previous valid conditions:
`!equal && multiplier <= 12`
`!equal && multiplier > 12`
`equal && multiplier > 12`
Now:
`!equal && multiplier <= 12`
> enforced stricter loop condition, added explanation

- build.gradle
The javax.mail package had a group name / package name change. The actual class path stayed the same.
> Update javax.mail group / package dependency

- src/main/java/net/fortuna/ical4j/transform/recurrence/AbstractDateExpansionRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByDayRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByHourRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByMinuteRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByMonthDayRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByMonthRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/BySecondRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByWeekNoRule.java
- src/main/java/net/fortuna/ical4j/transform/recurrence/ByYearDayRule.java
- src/test/groovy/net/fortuna/ical4j/model/RecurSpec.groovy
We found out that the system default timezone had inflcuence on the
results returned from Recur.getDates().
E.g. for FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;BYHOUR=0;BYMINUTE=5
you get different results when calling getDates with periodStart and
periodEnd in timezone Europe/Berlin while running the jvm with
-Duser.timezone=America/St_Johns vs. -Duser.timezone=America/Phoenix.
This turned out to be a problem with using Calendar's getTime() method to retrieve a java.util.Date
which is then passed to Dates.getInstance() losing the Calendar's TimeZone.
I have added a test case which detects the issue.
> Fix timezones depending on system default in Recur

- src/main/java/net/fortuna/ical4j/model/component/Observance.java
PR #488, commit cfc5c583, moved the setting  of initialOnsetUTC to the beginning of getLatestOnset().
Before cfc5c583, getLatestOnset() could return early without setting initialOnsetUTC.
This PR makes initialOnsetUTC an instance variable (like initialOnset) so it is only set once.
Fixes issue #506
> make initialOnsetUTC an instance variable

- src/main/java/net/fortuna/ical4j/model/TemporalAmountAdapter.java
Durations that did not parse correctly in our first sample set:
DURATION:P10M
DURATION:P115M
DURATION:P15M
DURATION:P30M
DURATION:P45M
DURATION:P60M
DURATION:P80M
DURATION:P90M
> Fix handling of intra-day durations that lack the T flag

- src/main/java/net/fortuna/ical4j/model/TimeZoneLoader.java
The Map-based TimeZoneCache-Implementation will be used by default now.
Set SystemProperty net.fortuna.ical4j.timezone.cache.impl to "net.fortuna.ical4j.util.JCacheTimeZoneCache" and provide a JCache-Implentation in the classpath to use JCache.
This should fix https://github.com/ical4j/ical4j/issues/195 as well.
> Change default implementation of TimeZoneCache to Map-based variant.

- build.gradle
- src/main/java/net/fortuna/ical4j/model/parameter/Email.java
- src/test/groovy/net/fortuna/ical4j/model/parameter/EmailTest.groovy
as in the issue, the import of com.sun.mail is old, it became jakarta.mail so we have to import jakarta mail lib since 2019
> fix for com.sun.mail lib import issue instead of jakarta mail

- .github/workflows/gradle.yml
- build.gradle
- src/test/groovy/net/fortuna/ical4j/model/DateTimeSpec.groovy
in follow up to the previous PR. This makes sure those tests will pass on any machine by setting default timezone to UTC when tests are run. I also fixed some deprecation warnings for Jacoco and made sure that reports are generated and enabled a test that is working
> Make sure tests are run with UTC timezone as default

- src/main/java/net/fortuna/ical4j/model/Recur.java
Fixed the return type for the `Recur.Builder` `rscale` and `skip` methods in order not to declare raw return type.
> Fixed the return type for the Recur.Builder rscale and skip methods

- .github/workflows/gradle.yml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- updated some GH actions to use more recent versions
- updated gradle wrapper to 7.6 (using v8 will require more changes)
- bumped Groovy to 3.0.17 (to get build working on JDK 19)
- bumped max JDK version used to be 19 (gradle doesn't support JDK 20 yet)
> update GH Actions to use v3

- src/main/java/net/fortuna/ical4j/model/PropertyCodec.java
- src/test/groovy/net/fortuna/ical4j/model/PropertyCodecTest.groovy
I've removed `"` from the list of escaping characters, and added a test to make sure it's not being escaped. See #641 for more information.
Fixes #641.
> Text property (e.g. DESCRIPTION) escapes DQUOTE without need

- .github/workflows/codeql-analysis.yml
- .github/workflows/gradle.yml
- .github/workflows/run-build.yml
- .github/workflows/scorecards.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Please treat this PR as for information only. I was taking a look at what breaking changes to expect when updating Gradle to latest v8 (8.4 currently) so that builds can be done with JDK 21.
Issues #632 and #658 are opened already for related issues that should be dealt with in individual PR's prior to updating the Gradle version.
> relates to [#632,#658]: highlighting some changes that will be needed when updating to Gradle 8.x

- src/main/resources/META-INF/native-image/com.fortuna.ical4j/reflect-config.json
- src/main/resources/META-INF/native-image/com.fortuna.ical4j/resource-config.json
This allows ical4j to work out of the box with Oracle [GraalVM](https://graalvm.org)'s native compilation.
> Add native-image metadata for GraalVM

- README.md
Should link to https://www.ical4j.org/examples/, linked to https://www.ical4j.org/examples/overview/ which is a 404
> Fix link to examples in README.md

- build.gradle
- gradle.properties
spock, groovy and junit were disagreeing on versions, leading to split package errors when building on Nix.
Fixes #725
> Align groovy and hamcrest versions

- .github/workflows/run-build.yml
`push` only triggers for branches within the repo, adding `pull_request` makes it also run for external PRs
> Run Gradle CI on PRs

- src/test/groovy/net/fortuna/ical4j/model/RecurSpec.groovy
https://www.rfc-editor.org/rfc/rfc5545#section-3.8.5.3 says:
```
The "DTSTART" property
value SHOULD be synchronized with the recurrence rule, if
specified.  The recurrence set generated with a "DTSTART" property
value not synchronized with the recurrence rule is undefined.
```
... so pick a start date that is on a Sunday.
This way the behavior of this test also no longer depends
on on which day of the week the week starts.
Fixes #727
> Change expectation of RecurSpec for intervals

- src/main/java/net/fortuna/ical4j/model/TemporalAmountAdapter.java
- src/test/groovy/net/fortuna/ical4j/model/TemporalAmountAdapterTest.groovy
Closes #731
This confirms the problem is timezone-related: the test succeeds when setting the default timezone to
`Australia/Melbourne` and fails when it's set to
`Europe/Amsterdam`. Before applying this change, however we should double-check that it's OK that this behavior depends on the default timezone, and that it's not a bug that it depends on it.
> Fixate timezone in P1D test

- src/main/java/net/fortuna/ical4j/validate/schema/JsonSchemaValidator.java
Quick fix for javadoc warning:
```
src/main/java/net/fortuna/ical4j/validate/schema/JsonSchemaValidator.java:46: warning: invalid input: '<'
* method added in Java 10. As such this will cause an error when used with Java < 10.
```
> Fix Javadoc warning in JsonSchemaValidator

- src/main/java/net/fortuna/ical4j/model/parameter/TzId.java
- src/test/groovy/net/fortuna/ical4j/model/VTimezoneTest.groovy
fixes #744 
If VTIMEZONE is defined but TZID is not in VTIMEZONE, fallback to GlobalZone, rather than throwing exception.
I've added a new test-case `model/VTimezoneTest.groovy`, which fails without the fix to `TzId.java`
> Fallback to GlobalZone if TZID not in VTIMEZONE
